In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [13]:
df = pd.read_csv("../data/raw/Training Data.csv")

In [14]:
df.head()

,Id,Income,Age,Experience,Married/Single,House_Ownership,Car_Ownership,Profession,CITY,STATE,CURRENT_JOB_YRS,CURRENT_HOUSE_YRS,Risk_Flag
0,1,1303834,23,3,single,rented,no,Mechanical_engineer,Rewa,Madhya_Pradesh,3,13,0
1,2,7574516,40,10,single,rented,no,Software_Developer,Parbhani,Maharashtra,9,13,0
2,3,3991815,66,4,married,rented,no,Technical_writer,Alappuzha,Kerala,4,10,0
3,4,6256451,41,2,single,rented,yes,Software_Developer,Bhubaneswar,Odisha,2,12,1
4,5,5768871,47,11,single,rented,no,Civil_servant,Tiruchirappalli[10],Tamil_Nadu,3,14,1

In [15]:
df.drop(columns=["Id"], inplace=True)

In [16]:
X= df.drop('Risk_Flag',axis=1)
y= df['Risk_Flag']

In [17]:
X.select_dtypes(include=['object']).columns

C:\Users\Hitanshi\AppData\Local\Temp\ipykernel_16344\754427252.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  X.select_dtypes(include=['object']).columns

Index(['Married/Single', 'House_Ownership', 'Car_Ownership', 'Profession',
       'CITY', 'STATE'],
      dtype='str')

In [18]:
df['CITY'].nunique()

317

In [19]:
df['Profession'].nunique()

51

In [20]:
df['STATE'].nunique()

29

In [21]:
X = pd.get_dummies(X, drop_first=True)

In [22]:
X.head()

,Income,Age,Experience,CURRENT_JOB_YRS,CURRENT_HOUSE_YRS,Married/Single_single,House_Ownership_owned,House_Ownership_rented,Car_Ownership_yes,Profession_Analyst,...,STATE_Punjab,STATE_Rajasthan,STATE_Sikkim,STATE_Tamil_Nadu,STATE_Telangana,STATE_Tripura,STATE_Uttar_Pradesh,STATE_Uttar_Pradesh[5],STATE_Uttarakhand,STATE_West_Bengal
0,1303834,23,3,3,13,True,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,7574516,40,10,9,13,True,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,3991815,66,4,4,10,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
3,6256451,41,2,2,12,True,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
4,5768871,47,11,3,14,True,False,True,False,False,...,False,False,False,True,False,False,False,False,False,False

In [24]:
X.shape

(252000, 403)

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)